name: GCP_Deployment

on: push

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3                                         
      - uses: actions/setup-python@v3                                     
        with:
          python-version: 3.9.10
      - uses: 'google-github-actions/auth@v0.7.3'                             
        with:
          service_account: 'tajp-540@website-chatbot-355122.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/1069608427194/locations/global/workloadIdentityPools/github_website/providers/github-website'
