name: GCP_Deployment

on: push

jobs:  
  config_creds_id:
  
    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.7.3'
      with:
        workload_identity_provider: 'projects/1069608427194/locations/global/workloadIdentityPools/github_website/providers/github-website'
        service_account: 'tajp-540@website-chatbot-355122.iam.gserviceaccount.com'
